# Generated by Django 5.2.3 on 2025-11-29 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chama', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_name', models.CharField(max_length=100)),
                ('cycle_type', models.CharField(choices=[('fixed_rota', 'Fixed Rota'), ('manual', 'Manual Selection'), ('merrygoround', 'Merry-Go Round'), ('shared_split', 'Shared Split')], max_length=20)),
                ('cycle_amount_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cycle_deadline', models.DateField()),
                ('cycle_status', models.CharField(default='open', max_length=20)),
                ('cycle_created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle_beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_beneficiary', to=settings.AUTH_USER_MODEL)),
                ('cycle_chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='chama.chama')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_type', models.CharField(choices=[('contribution', 'Contribution'), ('penalty', 'Penalty'), ('loan_repayment', 'Loan Repayment'), ('registration_fee', 'Registration Fee')], db_index=True, default='contribution', max_length=20)),
                ('contribution_mpesa_receipt', models.CharField(blank=True, max_length=20, null=True)),
                ('contribution_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('contribution_phone', models.CharField(max_length=15)),
                ('contribution_time', models.DateTimeField()),
                ('contribution_created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution_updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chama.chama')),
                ('contribution_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contribution_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='finance.contributioncycle')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('loan_total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_purpose', models.CharField(max_length=255)),
                ('loan_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('loan_deadline', models.DateField()),
                ('loan_outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='chama.chama')),
                ('loan_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_repayment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_repayment_time', models.DateTimeField(auto_now_add=True)),
                ('loan_repayment_mpesa_receipt', models.CharField(blank=True, max_length=20, null=True)),
                ('loan_repayment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_repayment_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='finance.loan')),
                ('loan_repayment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_amount', models.FloatField()),
                ('penalty_reason', models.TextField()),
                ('penalty_created_at', models.DateTimeField(auto_now_add=True)),
                ('penalty_chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chama.chama')),
                ('penalty_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
