# Generated by Django 5.2.3 on 2025-12-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='penalty_paid',
            field=models.BooleanField(default=False),
        ),
    ]
