# Generated by Django 5.2.3 on 2025-12-01 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chama', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=200)),
                ('meeting_date', models.DateTimeField()),
                ('meeting_type', models.CharField(choices=[('physical', 'Physical'), ('online', 'Online')], default='physical', max_length=20)),
                ('meeting_venue', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_online_link', models.URLField(blank=True, null=True)),
                ('meeting_agenda', models.TextField()),
                ('meeting_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('meeting_created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chama.chama')),
                ('meeting_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='absent', max_length=10)),
                ('attendance_timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendance_notes', models.TextField(blank=True, null=True)),
                ('attendance_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.meeting')),
                ('attendance_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_message', models.TextField()),
                ('notification_type', models.CharField(choices=[('reminder', 'Reminder'), ('loan', 'Loan'), ('payment', 'Payment'), ('meeting', 'Meeting'), ('announcement', 'Announcement'), ('member_joined', 'Member Joined'), ('transaction', 'Transaction'), ('penalty', 'Penalty')], max_length=30)),
                ('notification_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('notification_is_read', models.BooleanField(default=False)),
                ('notification_created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_updated_at', models.DateTimeField(auto_now=True)),
                ('notification_chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chama.chama')),
                ('notification_related_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_notifications', to='finance.contribution')),
                ('notification_related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_notifications', to='finance.loan')),
                ('notification_related_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to='notification.meeting')),
                ('notification_related_penalty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_notifications', to='finance.penalty')),
                ('notification_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('notification_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_reminder', to='notification.notification'),
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_method', models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email'), ('inapp', 'In-App')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_reply_message', models.TextField()),
                ('notification_reply_created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_reply_attachment', models.FileField(blank=True, null=True, upload_to='notification_replies/')),
                ('notification_parent_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_replies', to='notification.notificationreply')),
                ('notification_reply_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
                ('notification_reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_notification_settings_allow_sms', models.BooleanField(default=True)),
                ('user_notification_settings_allow_email', models.BooleanField(default=True)),
                ('user_notification_settings_allow_inapp', models.BooleanField(default=True)),
                ('user_notification_settings_fallback', models.BooleanField(default=True)),
                ('user_notification_settings_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
