# Generated by Django 5.2.3 on 2025-10-23 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chama_name', models.CharField(max_length=50)),
                ('chama_description', models.CharField(max_length=100)),
                ('chama_created_at', models.DateTimeField(auto_now_add=True)),
                ('chama_contribution_amount', models.FloatField()),
                ('chama_contribution_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('chama_custom_frequency_days', models.PositiveIntegerField(blank=True, help_text='If custom, enter number of days between contributions.', null=True)),
                ('chama_max_members', models.PositiveIntegerField(default=10)),
                ('chama_rota_type', models.CharField(choices=[('fixed', 'Fixed Order'), ('random', 'Randomized'), ('manual', 'Manual Selection')], default='fixed', max_length=14)),
                ('chama_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_request_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=8)),
                ('join_request_requested_at', models.DateTimeField(auto_now_add=True)),
                ('join_request_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('join_request_chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='chama.chama')),
                ('join_request_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL)),
                ('join_request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_join_date', models.DateTimeField(auto_now_add=True)),
                ('membership_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('membership_role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary')], default='member', max_length=9)),
                ('membership_chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chama.chama')),
                ('membership_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
