# Generated by Django 5.2.3 on 2025-11-22 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chama', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction_checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_mpesa_receipt', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_internal_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_type', models.CharField(choices=[('contribution', 'Contribution'), ('penalty', 'Penalty'), ('loan_repayment', 'Loan Repayment'), ('registration_fee', 'Registration Fee')], db_index=True, max_length=20)),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('transaction_created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_chama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daraja_transactions', to='chama.chama')),
                ('transaction_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daraja_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['transaction_user', 'transaction_status'], name='darajaapi_t_transac_366dfe_idx'), models.Index(fields=['transaction_chama', 'transaction_type'], name='darajaapi_t_transac_9c1ed4_idx'), models.Index(fields=['transaction_internal_reference'], name='darajaapi_t_transac_2388c5_idx')],
            },
        ),
    ]
